package org.apache.hupa.vaadin.mobile;

import org.apache.hupa.vaadin.actions.LoginActivity.LoginDisplay;

import com.vaadin.addon.touchkit.ui.DatePicker;
import com.vaadin.addon.touchkit.ui.EmailField;
import com.vaadin.addon.touchkit.ui.NavigationView;
import com.vaadin.addon.touchkit.ui.Switch;
import com.vaadin.addon.touchkit.ui.VerticalComponentGroup;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbstractTextField;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class MobileLoginView extends NavigationView implements LoginDisplay {

    private CheckBox cSmtpSecure;
    private TextField tSmtpPort;
    private TextField tSmtpServer;
    private CheckBox cImapSecure;
    private TextField tImapPort;
    private TextField tImapServer;
    private Button bLogin;
    private PasswordField fPassword;
    private TextField fUser;
    
    public MobileLoginView() {
        setCaption("Login");
        
        VerticalComponentGroup vLogin = new VerticalComponentGroup();

        fUser = new EmailField("Email");
        fUser.setInputPrompt("Enter your email address...");
        vLogin.addComponent(fUser);
        
        fPassword = new PasswordField("Password");
        vLogin.addComponent(fPassword);
        
        VerticalComponentGroup vConf = new VerticalComponentGroup();
        tImapServer = new TextField("IMAP server");
        vConf.addComponent(tImapServer);
        tImapPort = new TextField("IMAP port");
        vConf.addComponent(tImapPort);
        cImapSecure = new Switch("IMAP secure");
        vConf.addComponent(cImapSecure);
        tSmtpServer = new TextField("SMTP server");
        vConf.addComponent(tSmtpServer);
        tSmtpPort = new TextField("SMTP port");
        vConf.addComponent(tSmtpPort);
        cSmtpSecure = new Switch("SMTP secure");
        vConf.addComponent(cSmtpSecure);
        
        bLogin = new Button("Submit");
        setContent(new CssLayout(vLogin, bLogin, vConf));
    }

    @Override
    public void show() {
        UI.getCurrent().setContent(this);
    }
    @Override
    public void hide() {
    }
    @Override
    public Button getbLogin() {
        return bLogin;
    }
    @Override
    public PasswordField getfPassword() {
        return fPassword;
    }
    @Override
    public TextField getfUser() {
        return fUser;
    }
    @Override
    public CheckBox getcSmtpSecure() {
        return cSmtpSecure;
    }
    @Override
    public TextField gettSmtpPort() {
        return tSmtpPort;
    }
    @Override
    public TextField gettSmtpServer() {
        return tSmtpServer;
    }
    @Override
    public CheckBox getcImapSecure() {
        return cImapSecure;
    }
    @Override
    public TextField gettImapPort() {
        return tImapPort;
    }
    @Override
    public TextField gettImapServer() {
        return tImapServer;
    }  

}
